# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=30)),
                ('grade_book', models.CharField(max_length=30)),
                ('discount_book', models.IntegerField(default=3)),
                ('major_book', models.CharField(max_length=30)),
                ('photo_book', models.FileField(upload_to='./upload/')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
